- name: deploy to prod
  gather_facts: no
  hosts: qutex
  tasks:
    - name: Release Date
      debug:
        msg: >
          Release Date: '{{ QUTEX_RELEASE_DATE }}'
          Version: '{{ QUTEX_VERSION }}'
          Image: 'docker.pkg.github.com/amthorn/qutex/qutex_bot:{{ QUTEX_VERSION }}
    - name: Copy file with owner and permission, using symbolic representation
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: '{{ SRC }}/docker-compose.yml'
        owner: centos
        group: centos
        mode: u=rw,g=r,o=r
    - name: Do deployment
      environment:
        QUTEX_RELEASE_DATE: "{{ QUTEX_RELEASE_DATE }}"
        QUTEX_VERSION: "{{ QUTEX_VERSION }}"
        QUTEX_IMAGE: docker.pkg.github.com/amthorn/qutex/qutex_bot:{{ QUTEX_VERSION }}
      ansible.builtin.shell:
        chdir: '{{ SRC }}'
        cmd: |
          docker-compose pull
          docker-compose down
          docker-compose up -d