- name: deploy to prod
  gather_facts: no
  hosts: qutex
  tasks:
    - name: Release Date
      debug:
        msg: >
          Release Date: '{{ QUTEX_RELEASE_DATE }}'
          Version: '{{ QUTEX_VERSION }}'
          Image: 'docker.pkg.github.com/amthorn/qutex/qutex_bot:{{ QUTEX_VERSION }}'
    - name: Confirm?
      pause:
        prompt: Press return to continue. Press Ctrl+c and then "a" to abort
    - name: Do deployment
      environment:
        QUTEX_RELEASE_DATE: "{{ QUTEX_RELEASE_DATE }}"
        QUTEX_VERSION: "{{ QUTEX_VERSION }}"
        QUTEX_IMAGE: docker.pkg.github.com/amthorn/qutex/qutex_bot:{{ QUTEX_VERSION }}
      ansible.builtin.shell:
        chdir: '{{ SRC }}'
        cmd: |
          docker-compose pull
          docker-compose down
          docker-compose up -d