version: '3.3'
services:
    bot:
        command: start:dev
        tty: true
        environment:
            NODE_ENV: development
        volumes: 
            - ./services/bot:/app
            - ./services/bot/tsconfig.json:/app/tsconfig.json
            - ./services/bot/package.json:/app/package.json
    mongo:
        ports:
            - 27017:27017