version: '3.9'
services:
    nginx:
        depends_on:
            - web
            - auth
            - projects
        restart: always
        build:
            context: services/nginx
        ports:
            - 80:80
    bot:
        image: ${QUTEX_IMAGE:-qutex_bot:latest}
        restart: always
        depends_on: 
            - mongo
        ports:
            -   target: 3000
                published: 3000
                mode: host
        environment:
            NODE_ENV: production
            VERSION: ${QUTEX_VERSION}
            RELEASE_DATE: ${QUTEX_RELEASE_DATE}
            AUTHOR_NAME: Ava Thorn
            AUTHOR_EMAIL: avatheavian@gmail.com
            DEBUG_EMAIL: avthorn@cisco.com
            SUPER_ADMINS: '["Y2lzY29zcGFyazovL3VzL1BFT1BMRS9kODRkZjI1MS1iYmY3LTRlZTEtOTM1OS00Y2I0MGIyOTBhN2I"]'
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
        secrets:
            - token
            - mongoPassword
    ui:
        restart: always
        depends_on:
            - mongo
            - bot
            # - api
        build:
            context: services/ui/
        env_file:
            - .production.env
    projects:
        depends_on:
            - mongo
            - auth
        restart: always
        build:
            context: .
            dockerfile: services/_api_service_template/Dockerfile
            args:
                SERVICE_PREFIX: projects
        env_file:
            - .production.env
        secrets:
            - mongoPassword
    users:
        depends_on:
            - auth
        restart: always
        build:
            context: .
            dockerfile: services/_api_service_template/Dockerfile
            args:
                SERVICE_PREFIX: users
        env_file:
            - .production.env
        secrets:
            - token
            - mongoPassword
    auth: 
        depends_on:
            - redis
            - mongo
        restart: always
        build:
            context: .
            dockerfile: services/_api_service_template/Dockerfile
            args:
                SERVICE_PREFIX: auth
        env_file:
            - .production.env
        secrets:
            - privateKey
            - token
            - mongoPassword
    redis: 
        restart: always
        image: redis:6.2.1
    migrate:
        depends_on: 
            - mongo
        image: ${QUTEX_IMAGE:-qutex_bot:latest}
        environment:
            NODE_ENV: production
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
        secrets:
            - mongoPassword
        entrypoint: node_modules/migrate-mongo/bin/migrate-mongo.js
        command: up
        # command: down  # undo-last
        # command: status  # status
    mongo:
        image: mongo:4.4.5
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongoPassword
        volumes:
            - mongo_volume:/data/db
        secrets:
            - mongoPassword
secrets:
    token:
        file: secrets/prod/token
    mongoPassword:
        file: secrets/prod/mongoPassword
    privateKey:
        file: secrets/prod/privateKey
volumes:
    mongo_volume:
