version: '3.9'
x-env_files: &env_files
    - .production.env
    - .version.env
x-common: &common
    restart: always
    env_file: *env_files
services:
    nginx:
        <<: *common
        image: ghcr.io/amthorn/qutex/qutex_nginx:${QUTEX_VERSION:-latest}
        depends_on:
            # - ui
            # - auth
            # - projects
            # - users
            - bot
        environment:
            CERTBOT_EMAIL: avatheavian@gmail.com
            RENEWAL_INTERVAL: 8d
        volumes:
            - cert_files:/etc/letsencrypt
        ports:
            -   target: 80
                published: 80
                mode: host
            -   target: 443
                published: 443
                mode: host
        restart: always
    bot:
        <<: *common
        image: ghcr.io/amthorn/qutex/qutex_bot:${QUTEX_VERSION:-latest}
        depends_on: 
            - mongo
        # ports:
        #     -   target: 3000
        #         published: 3000
        #         mode: host
        secrets:
            - token
            - mongoPassword
    # ui:
    #     <<: *common
    #     image: ghcr.io/amthorn/qutex/qutex_ui:${QUTEX_VERSION:-latest}
    #     depends_on:
    #         - mongo
    #         - bot
    #         # - api
    #     build:
    #         context: services/ui/
    # projects:
    #     <<: *common
    #     image: ghcr.io/amthorn/qutex/qutex_projects:${QUTEX_VERSION:-latest}
    #     depends_on:
    #         - mongo
    #         - auth
    #     secrets:
    #         - mongoPassword
    # users:
    #     <<: *common
    #     image: ghcr.io/amthorn/qutex/qutex_users:${QUTEX_VERSION:-latest}
    #     depends_on:
    #         - auth
    #     secrets:
    #         - token
    #         - mongoPassword
    # auth: 
    #     <<: *common
    #     image: ghcr.io/amthorn/qutex/qutex_auth:${QUTEX_VERSION:-latest}
    #     depends_on:
    #         - redis
    #         - mongo
    #     secrets:
    #         - privateKey
    #         - token
    #         - mongoPassword
    # redis: 
    #     restart: always
    #     image: redis:6.2.1
    migrate:
        depends_on: 
            - mongo
        image: ghcr.io/amthorn/qutex/qutex_bot:${QUTEX_VERSION:-latest}
        env_file: *env_files
        secrets:
            - mongoPassword
        entrypoint: node_modules/migrate-mongo/bin/migrate-mongo.js
        command: up
        # command: down  # undo-last
        # command: status  # status
    mongo:
        <<: *common
        image: mongo:4.4.5
        volumes:
            - mongo_volume:/data/db
        secrets:
            - mongoPassword
    # mongo_ui:
    #     image: mongo-express:1.0.0-alpha
    #     depends_on:
    #         - mongo
    #     environment:
    #         ME_CONFIG_MONGODB_SERVER: mongo
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #         ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongoPassword
    #         ME_CONFIG_SITE_BASEURL: /admin/mongo/
    #         ME_CONFIG_OPTIONS_NO_DELETE: "true"
    #         ME_CONFIG_OPTIONS_READONLY: "true"
    #         ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    #     secrets:
    #         - mongoPassword
    mongo_backup:
        image: ghcr.io/amthorn/qutex/qutex_mongo_backup:${QUTEX_VERSION:-latest}
        environment:
            MONGODB_HOST: mongo
            MONGODB_PORT: 27017
            MONGODB_USER: root
            MONGODB_PASS_FILE: /run/secrets/mongoPassword
            CRON_TIME: 0 0 * * *
            EXTRA_OPTS: --authenticationDatabase admin --db qutex --gzip --forceTableScan
            MAX_BACKUPS: 14
            INIT_BACKUP: 1
        volumes: 
            - ./mongo_backups:/backup
        secrets:
            - mongoPassword
    # redis_ui:
    #     image: rediscommander/redis-commander
    #     environment:
    #         REDIS_HOST: redis
    #         REDIS_PORT: "6379"
    #         URL_PREFIX: /admin/redis
    #     ports:
    #         - 8081:8081
secrets:
    token:
        file: secrets/prod/token
    mongoPassword:
        file: secrets/prod/mongoPassword
    privateKey:
        file: secrets/prod/privateKey
volumes:
    mongo_volume:
    cert_files:
