version: '3.3'
services:
    bot:
        image: qutex_bot:latest
        build:
            context: ./services/bot
        ports:
            - 3000:3000
        env_file:
            - settings.env
            - mongo.env
        environment:
            NODE_ENV: production
        secrets:
            - token
            - mongoPassword
    migrate:
        depends_on: 
            - mongo
        image: qutex_bot:latest
        build:
            context: ./services/bot
        env_file:
            - mongo.env
        environment:
            NODE_ENV: production
        secrets:
            - mongoPassword
        entrypoint: migrate-mongo
        command: up
        # command: down  # undo-last
        # command: status  # status
    mongo:
        image: mongo:4.4.5
        restart: always
        env_file:
            - mongo.env
        environment:
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongoPassword
        volumes:
            - mongo_volume:/data/db
        secrets:
            - mongoPassword
secrets:
    token:
        file: token
    mongoPassword:
        file: mongoPassword
volumes:
    mongo_volume: