version: '3.3'
services:
    bot:
        image: ${QUTEX_IMAGE:-qutex_bot:latest}
        restart: always
        depends_on: 
            - mongo
        ports:
            - 3000:3000
        environment:
            NODE_ENV: production
            VERSION: ${QUTEX_VERSION}
            RELEASE_DATE: ${QUTEX_RELEASE_DATE}
            AUTHOR_NAME: Ava Thorn
            AUTHOR_EMAIL: avatheavian@gmail.com
            SUPER_ADMINS: '["Y2lzY29zcGFyazovL3VzL1BFT1BMRS9kODRkZjI1MS1iYmY3LTRlZTEtOTM1OS00Y2I0MGIyOTBhN2I"]'
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
        secrets:
            - token
            - mongoPassword
        healthcheck:  
            test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
            interval: 1m30s
            timeout: 10s
            retries: 3
    migrate:
        depends_on: 
            - mongo
        image: ${QUTEX_IMAGE:-qutex_bot:latest}
        environment:
            NODE_ENV: production
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
        secrets:
            - mongoPassword
        entrypoint: node_modules/migrate-mongo/bin/migrate-mongo.js
        command: up
        # command: down  # undo-last
        # command: status  # status
    mongo:
        image: mongo:4.4.5
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_DATABASE: qutex
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongoPassword
        volumes:
            - mongo_volume:/data/db
        secrets:
            - mongoPassword
secrets:
    token:
        file: token
    mongoPassword:
        file: mongoPassword
volumes:
    mongo_volume: