version: '3.9'
x-env_files: &env_files
    - .production.env
    - .version.env
x-common: &common
    restart: always
    env_file: *env_files
services:
    nginx:
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_nginx:${QUTEX_VERSION:-latest}
        depends_on:
            - web
            - auth
            - projects
        ports:
            - 80:80
    bot:
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_bot:${QUTEX_VERSION:-latest}
        depends_on: 
            - mongo
        ports:
            -   target: 3000
                published: 3000
                mode: host
        secrets:
            - token
            - mongoPassword
    ui:
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_ui:${QUTEX_VERSION:-latest}
        depends_on:
            - mongo
            - bot
            # - api
        build:
            context: services/ui/
    projects:
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_projects:${QUTEX_VERSION:-latest}
        depends_on:
            - mongo
            - auth
        secrets:
            - mongoPassword
    users:
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_users:${QUTEX_VERSION:-latest}
        depends_on:
            - auth
        secrets:
            - token
            - mongoPassword
    auth: 
        <<: *common
        image: docker.pkg.github.com/amthorn/qutex/qutex_auth:${QUTEX_VERSION:-latest}
        depends_on:
            - redis
            - mongo
        secrets:
            - privateKey
            - token
            - mongoPassword
    redis: 
        restart: always
        image: redis:6.2.1
    migrate:
        depends_on: 
            - mongo
        image: docker.pkg.github.com/amthorn/qutex/qutex_bot:${QUTEX_VERSION:-latest}
        env_file: *env_files
        secrets:
            - mongoPassword
        entrypoint: node_modules/migrate-mongo/bin/migrate-mongo.js
        command: up
        # command: down  # undo-last
        # command: status  # status
    mongo:
        <<: *common
        image: mongo:4.4.5
        volumes:
            - mongo_volume:/data/db
        secrets:
            - mongoPassword
secrets:
    token:
        file: secrets/prod/token
    mongoPassword:
        file: secrets/prod/mongoPassword
    privateKey:
        file: secrets/prod/privateKey
volumes:
    mongo_volume:
