
site_name: Qutex
repo_url: https://github.com/amthorn/qutex
site_description: The documentation pages for qutex
site_author: Ava Thorn
copyright: Copyright &copy; 2021 Ava Thorn
strict: true
edit_uri: ''
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amthorn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ava-thorn-384059135/
extra_css:
  - css/hint.min.css
extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: images/logoSquareSmall.png
  custom_dir: docs/overrides
  features:
    - header.autohide
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - tooltips
  - macros:
      include_dir: docs/blocks
markdown_extensions:
  - admonition            # Permits admonitions
  - pymdownx.details      # Permits collapsible admonitions
  - pymdownx.tabbed       # Permits tabs in code blocks/admonitions
  - pymdownx.superfences  # Permits code within admonitions
  - attr_list             # Permits aligning images left/right
  - pymdownx.emoji:       # Used for displaying icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:  # Allows mathematical formulas (used in some of the analytics and the "how long" command)
      generic: true
nav:
    - Introduction: index.md
    - Authorization: authorization.md
    - Projects: projects.md
    - Queues: queues.md
    - Registrations: registrations.md
    - Administration: administration.md
    - Analytics: analytics.md
    - Command List: command_list.md
    - API: api.md
    - Easter Eggs: eggs.md
    - Troubleshooting: troubleshooting.md
    - Known Issues: known_issues.md
