name: Continuous Integration

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.save-deps.outputs.cache-hit != 'true'
        uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/node install
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/node lint
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo apt-get install -y mongodb-org=3.6.14 mongodb-org-server=3.6.14 mongodb-org-shell=3.6.14 mongodb-org-mongos=3.6.14 mongodb-org-tools=3.6.14
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/node test --silent