name: Continuous Integration

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.save-deps.outputs.cache-hit != 'true'
        uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/bot install
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - run: ./services/bot/bin/lint.sh
      - uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/bot lint
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/set-timezone-action@v1.1
        with:
          timezoneLinux: "America/New_York"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - run: echo `openssl rand -hex 64` >> mongoPassword
      - run: echo "DOESNTMATTER" >> token
      - run: sudo docker run -v $(pwd)/mongoPassword:/run/secrets/mongoPassword -e MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongoPassword --env-file mongo.env --name mongo -d -p 27017:27017 mongo:4.4.5
      - run: yarn --cwd services/bot test --silent