name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.14.0
      - uses: actions/checkout@${{ GITHUB_REF }}
      - uses: actions/cache@v2
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.save-deps.outputs.cache-hit != 'true'
        uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/bot install
      - run: pwd
      - run: ls -la
      - run: ls -la services
      - run: ls -la services/bot
      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: qutex_bot
          extract-git-tag: true
          build-context: ./services/bot