name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 15.14.0
      - uses: actions/checkout@master
      - uses: actions/cache@v3.0.3
        id: save-deps
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install Dependencies
        if: steps.save-deps.outputs.cache-hit != 'true'
        uses: CultureHQ/actions-yarn@master
        with:
          args: --cwd services/bot install
      - name: Build & push containers
        run: |
          # Setup Build
          docker login -u publisher -p ${DOCKER_TOKEN} ghcr.io

          ./bin/create_version.sh "${GITHUB_REF##*/}" 1
          
          # Build all containers
          QUTEX_VERSION=$(echo ${GITHUB_REF##*/}) docker compose -f docker-compose.yml -f docker-compose.build.yml build --no-cache
          QUTEX_VERSION=$(echo ${GITHUB_REF##*/}) docker compose -f docker-compose.yml -f docker-compose.build.yml push
        env:
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}